image:
  repository: ishaimou/votingapp_worker
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: worker
  clusterIP: None
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
replicaCount: 1
